name: 'Build Image'

on:
  push:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - 'renovate/**'

  release:
    types:
      - published

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/actions/.github/workflows/build-docker-image.yml@6c1e1155e0a1b5aaf975544e23d7ff490511a1d9 # v0.0.6
    with:
      image-name: ghcr.io/slashnephy/m2ts-classifier
      image-platforms: linux/amd64
