name: 'Build Image'

on:
  push:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - 'renovate/**'

  release:
    types:
      - published

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/actions/.github/workflows/build-docker-image.yml@f63926caa7aad32744d96b2129d04ea0d549e9fb # v0.0.5
    with:
      image-name: ghcr.io/slashnephy/m2ts-classifier
      image-platforms: linux/amd64
